apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp-color-deployment
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30010
      targetPort: 8080
